# Creating NumPy Arrays 

There are multiple ways to create numpy arrays, the most commmon ones being:
* Convert lists or tuples to arrays using ```np.array()```
* Initialise arrays of fixed size (when the size is known) 

The following ways are commonly used:
* ```np.ones()```: Create array of 1s
* ```np.zeros()```: Create array of 0s
* ```np.arange()```: Create array with increments of a fixed step size
* ```np.linspace()```: Create array of fixed length

In [3]:
# importing the NumPy library

import numpy as np

In [5]:
# creating an array with 4 elements and increments of a fixed step size
# default step size is one
np_1 = np.arange(1, 50, 3)


# creating an array of zeroes with 5 elements
np_2 = np.zeros(5, dtype='int')

In [6]:
# checking the created array: np_1
print(np_1)

[ 1  4  7 10 13 16 19 22 25 28 31 34 37 40 43 46 49]


In [ ]:
# checking the created array:np_2
print(np_2)

In [7]:
# data type of np_2
np_2.dtype

dtype('int64')

In [ ]:
# specifying the data type of the array in the provided attribute



In [8]:
# adding the two arrays: np_1 and np_2
print(np_1 + np_2)

ValueError: operands could not be broadcast together with shapes (17,) (5,) 

In [9]:
# check the dimension of the arrays
# array np_1
np_1.ndim

1

In [10]:
# check the dimension of the arrays
# array np_2
np_2.ndim

1

In [12]:
# creating a third array with all the 5 elements as ones

np_3 = np.ones(5, dtype='int')

# checking the created array:np_3
print(np_3)

[1 1 1 1 1]


In [ ]:
# check the dimension of the arrays
# array np_2


In [13]:
# subtracting the array np_3 from array np_2

print(np_2 - np_3)

[-1 -1 -1 -1 -1]


In [15]:
# creating an array of fixed length
np_4 = np.fix(5, 'ko')

# checking the created array:np_4
print(np_4)

TypeError: return arrays must be of ArrayType

In [ ]:
# checking the created array:np_1
np_1

In [ ]:
# squaring the terms of np_1


In [ ]:
# getting the absolute value of the elements


In [ ]:
# np.sin()
# np.cos()

In [ ]:
# np.log()

### Empty arrays

In [ ]:
# Creating empty arrays

x = np.arange(1, 6)
y = 

# filling the empty array


In [ ]:
# printing the output obtained above
y

### Aggregation of array elements

In [ ]:
# Reducing the elements to a single value based on addition


In [ ]:
# Cummulative addition of elements at each element


In [ ]:
np.linalg

In [13]:
help(np.linalg)

Help on package numpy.linalg in numpy:

NAME
    numpy.linalg

DESCRIPTION
    Core Linear Algebra Tools
    -------------------------
    Linear algebra basics:
    
    - norm            Vector or matrix norm
    - inv             Inverse of a square matrix
    - solve           Solve a linear system of equations
    - det             Determinant of a square matrix
    - lstsq           Solve linear least-squares problem
    - pinv            Pseudo-inverse (Moore-Penrose) calculated using a singular
                      value decomposition
    - matrix_power    Integer power of a square matrix
    
    Eigenvalues and decompositions:
    
    - eig             Eigenvalues and vectors of a square matrix
    - eigh            Eigenvalues and eigenvectors of a Hermitian matrix
    - eigvals         Eigenvalues of a square matrix
    - eigvalsh        Eigenvalues of a Hermitian matrix
    - qr              QR decomposition of a matrix
    - svd             Singular value decomposition 

## Additional functions to initialize arrays in NumPy

Apart from the methods mentioned above, there are a few more NumPy functions that you can use to create special NumPy arrays:

-  `np.full()`: Create a constant array of any number ‘n’
-  `np.tile()`: Create a new array by repeating an existing array for a particular number of times
-  `np.eye()`: Create an identity matrix of any dimension
* ```np.random.random()```: Create array of random numbers between 0 and 1
-  `np.random.randint()`: Create a random array of integers within a particular range

In [17]:
# Creating a 4 x 3 array of 7s using np.full()
# The default data type here is int only
np.full((4,3), 'mak')

array([['mak', 'mak', 'mak'],
       ['mak', 'mak', 'mak'],
       ['mak', 'mak', 'mak'],
       ['mak', 'mak', 'mak']], dtype='<U3')

In [19]:
# Given an array, np.tile() creates a new array by repeating the given array for any number of times that you want
# The default data type her is int only
arr = ([0, 1, 2])
np.tile(arr, 30)

array([0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0,
       1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1,
       2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2,
       0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0,
       1, 2])

In [20]:
# You can also create multidimensional arrays using np.tile()
np.tile(arr, (3,2))

array([[0, 1, 2, 0, 1, 2],
       [0, 1, 2, 0, 1, 2],
       [0, 1, 2, 0, 1, 2]])

In [22]:
# Create a 3 x 3 identity matrix using np.eye()
# The default data type here is float. So if we want integer values, we need to specify the dtype to be int
np.eye(7, dtype = int)

array([[1, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 1]])

In [29]:
# Create a 3 x 3 array of random numbers between 0 and 1
np.random.random([3, 4])

array([[0.90820845, 0.03657162, 0.13035845, 0.80519466],
       [0.92202891, 0.45928034, 0.01195886, 0.78965517],
       [0.78810261, 0.16201828, 0.18077666, 0.14515361]])

In [27]:
# Create a 4 x 4 random array of integers ranging from 0 to 9
np.random.randint(0, 10, (4, 3))

array([[1, 4, 5],
       [3, 3, 3],
       [0, 0, 0],
       [7, 3, 7]])

In [51]:
np.tile([[1,0], [0,1]], [4//2,2//2])

array([[1, 0],
       [0, 1],
       [1, 0],
       [0, 1]])

In [45]:
np.full(5, [1,0])

ValueError: could not broadcast input array from shape (2) into shape (5)

In [56]:
t5 = [[1, 5],
 [3, 7],
 [4, 9]];
np.reshape(t5, 2, 3)

ValueError: Non-string object detected for the array ordering. Please pass in 'C', 'F', 'A', or 'K' instead

In [69]:
arr7 = [[1, 2, 3, 4, 5],
 [6, 7, 8, 9, 10],
 [11, 12, 13, 14, 15],
 [16, 17, 18, 19, 20]];
t7 = np.array(arr7)

In [77]:
t7[t7 %2 != 0].reshape(5,2)

array([[ 1,  3],
       [ 5,  7],
       [ 9, 11],
       [13, 15],
       [17, 19]])

In [79]:
t7.reshape(5, 4)[t7%2 != 0]

ValueError: operands could not be broadcast together with shapes (5,4) (4,5) 

In [86]:
t8 = [[1, 5],
 [3, 7],
 [4, 9]]

l9 = np.reshape(t8, (1, -1))
l9.ndim

2

In [117]:
p1 = [[7, 13, 14],
[18, 10, 17],
[11, 12, 19]]
p2 = [16, 6, 1]
p3 = [[5, 8, 4, 3]]

np.hstack((np.vstack((p1, p2)), np.reshape(p3, (4, 1))))

array([[ 7, 13, 14,  5],
       [18, 10, 17,  8],
       [11, 12, 19,  4],
       [16,  6,  1,  3]])