In [7]:
import numpy as np

np.__version__

'1.18.5'

In [8]:
np.add

<ufunc 'add'>

In [9]:
help(np.add)

Help on ufunc object:

add = class ufunc(builtins.object)
 |  Functions that operate element by element on whole arrays.
 |  
 |  To see the documentation for a specific ufunc, use `info`.  For
 |  example, ``np.info(np.sin)``.  Because ufuncs are written in C
 |  (for speed) and linked into Python with NumPy's ufunc facility,
 |  Python's help() function finds this page whenever help() is called
 |  on a ufunc.
 |  
 |  A detailed explanation of ufuncs can be found in the docs for :ref:`ufuncs`.
 |  
 |  Calling ufuncs:
 |  ===============
 |  
 |  op(*x[, out], where=True, **kwargs)
 |  Apply `op` to the arguments `*x` elementwise, broadcasting the arguments.
 |  
 |  The broadcasting rules are:
 |  
 |  * Dimensions of length 1 may be prepended to either array.
 |  * Arrays may be repeated along dimensions of length 1.
 |  
 |  Parameters
 |  ----------
 |  *x : array_like
 |      Input arrays.
 |  out : ndarray, None, or tuple of ndarray and None, optional
 |      Alternate array o

In [20]:
np.any([0, 0, 0])

False

In [30]:
np.full((3, 3), True)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [42]:
s1 = np.arange(10) 
s1[s1 % 2 != 0]

array([1, 3, 5, 7, 9])

In [43]:
s1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [50]:
o1 = np.arange(10)
o1[s1 % 2 != 0] = -1
s1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [51]:
o1

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [55]:
q1 = np.arange(0, 10)

In [58]:
q1.reshape(2, -1)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [59]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

In [60]:
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [61]:
b

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [64]:
np.vstack((a, b))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [71]:
np.tile([1, 2, 3], 3)

array([1, 2, 3, 1, 2, 3, 1, 2, 3])

In [75]:
np.concatenate((np.repeat([1, 2, 3], 3), np.tile([1, 2, 3], 3)))

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [78]:
np.intersect1d([1, 3, 4, 3], [5, 1, 2, 1])

array([1])

In [81]:
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

np.union1d(a, b)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [83]:
np.setdiff1d(a, b)

array([1, 2, 3, 4])

In [92]:
s1 = np.tile('hello', (4, 2))
s1

array([['hello', 'hello'],
       ['hello', 'hello'],
       ['hello', 'hello'],
       ['hello', 'hello']], dtype='<U5')

In [97]:
s1.shape

(4, 2)

In [114]:
np.empty([4,2], dtype = np.uint16) 

array([[    0,     0],
       [    0, 45056],
       [14791, 49119],
       [ 2047, 45056]], dtype=uint16)

In [120]:
np.arange(10, 25, 5)
help(np.full)

Help on function full in module numpy:

full(shape, fill_value, dtype=None, order='C')
    Return a new array of given shape and type, filled with `fill_value`.
    
    Parameters
    ----------
    shape : int or sequence of ints
        Shape of the new array, e.g., ``(2, 3)`` or ``2``.
    fill_value : scalar
        Fill value.
    dtype : data-type, optional
        The desired data-type for the array  The default, None, means
         `np.array(fill_value).dtype`.
    order : {'C', 'F'}, optional
        Whether to store multidimensional data in C- or Fortran-contiguous
        (row- or column-wise) order in memory.
    
    Returns
    -------
    out : ndarray
        Array of `fill_value` with the given shape, dtype, and order.
    
    See Also
    --------
    full_like : Return a new array with shape of input filled with value.
    empty : Return a new uninitialized array.
    ones : Return a new array setting values to one.
    zeros : Return a new array setting values to

In [126]:
help(np.random.random)

Help on built-in function random:

random(...) method of numpy.random.mtrand.RandomState instance
    random(size=None)
    
    Return random floats in the half-open interval [0.0, 1.0). Alias for
    `random_sample` to ease forward-porting to the new random API.



In [128]:
np.empty((2, 4))

array([[0.11840924, 0.39646076, 0.94588416, 0.45857885],
       [0.32637618, 0.40356891, 0.30509941, 0.21926075]])

In [131]:
np.random.randint(5,size=(2,3))

array([[3, 3, 4],
       [3, 3, 2]])

In [132]:
help(np.linspace)

Help on function linspace in module numpy:

linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0)
    Return evenly spaced numbers over a specified interval.
    
    Returns `num` evenly spaced samples, calculated over the
    interval [`start`, `stop`].
    
    The endpoint of the interval can optionally be excluded.
    
    .. versionchanged:: 1.16.0
        Non-scalar `start` and `stop` are now supported.
    
    Parameters
    ----------
    start : array_like
        The starting value of the sequence.
    stop : array_like
        The end value of the sequence, unless `endpoint` is set to False.
        In that case, the sequence consists of all but the last of ``num + 1``
        evenly spaced samples, so that `stop` is excluded.  Note that the step
        size changes when `endpoint` is False.
    num : int, optional
        Number of samples to generate. Default is 50. Must be non-negative.
    endpoint : bool, optional
        If True, `stop` is

In [133]:
help(np.arange)

Help on built-in function arange in module numpy:

arange(...)
    arange([start,] stop[, step,], dtype=None)
    
    Return evenly spaced values within a given interval.
    
    Values are generated within the half-open interval ``[start, stop)``
    (in other words, the interval including `start` but excluding `stop`).
    For integer arguments the function is equivalent to the Python built-in
    `range` function, but returns an ndarray rather than a list.
    
    When using a non-integer step, such as 0.1, the results will often not
    be consistent.  It is better to use `numpy.linspace` for these cases.
    
    Parameters
    ----------
    start : number, optional
        Start of interval.  The interval includes this value.  The default
        start value is 0.
    stop : number
        End of interval.  The interval does not include this value, except
        in some cases where `step` is not an integer and floating point
        round-off affects the length of `out`.
   

In [139]:
np.arange(3,17,5)

array([ 3,  8, 13])

In [138]:
np.linspace(3, 17, 12)

array([ 3.        ,  4.27272727,  5.54545455,  6.81818182,  8.09090909,
        9.36363636, 10.63636364, 11.90909091, 13.18181818, 14.45454545,
       15.72727273, 17.        ])

In [150]:
np.random.randint(10, size=(2, 5))

array([[3, 4, 0, 1, 2],
       [8, 8, 9, 8, 7]])