In [15]:
import numpy as np

my_array = np.array([[1, 2, 3], [4, 5, 6]])
my_array

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
my_array[:, 1:3]

array([[2, 3],
       [5, 6]])

In [5]:
my_array[:, :] = my_array * 2
my_array

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [13]:
my_array

array([[1, 2, 3],
       [4, 5, 6]])

In [14]:
my_array = my_array * 2

my_array

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [30]:
o1 = np.identity(5, dtype='int')
np.fill_diagonal(o1[::-1], 1)
o1

array([[1, 0, 0, 0, 1],
       [0, 1, 0, 1, 0],
       [0, 0, 1, 0, 0],
       [0, 1, 0, 1, 0],
       [1, 0, 0, 0, 1]])

In [37]:
start = int(input("Enter Start Position: "))
increment = int(input("Enter gradual increment: "))
valueToCheck= int(input("Enter value to check whether it falls in AP or not"))
            
if (valueToCheck == 0):
    print("Not in AP")
else:
    arr = np.arange(start, (valueToCheck + 1), increment)
    print(arr)        
    if np.isin(valueToCheck, arr):
        print("In AP")
    else:
        print("Not in AP")

Enter Start Position: 1
Enter gradual increment: 7
Enter value to check whether it falls in AP or not8
[1 8]
In AP


In [42]:
class parent:
    def __init__(self, param):
        self.v1 = param

class child(parent):
    def __init__(self, param):
        super().__init__(param)
        self.v2 = param

obj = child('11')
print(obj.v1 + " " + obj.v2)

11 11


In [43]:
values = [1, 2, 1, 3]
nums = set(values)

def checkit(num):
    if num in nums:
        return True
    else:
        return False

for i in  filter(checkit, values):
    print(i)

1
2
1
3


In [44]:
np.zeros((4,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [47]:
o2 = np.random.randint(1, 100, size=(4, 5))
o2

array([[ 1, 13, 89, 81, 27],
       [11, 40,  7, 42, 24],
       [24,  9, 61, 14, 28],
       [72,  5, 16, 59, 90]])

In [49]:
o2[[0,-1]] 

array([[ 1, 13, 89, 81, 27],
       [72,  5, 16, 59, 90]])

In [51]:
o2[:,[0, -1]]

array([[ 1, 27],
       [11, 24],
       [24, 28],
       [72, 90]])

In [ ]:
inp = int(input('Enter matrix dimension: '))
o3 = np.zeros((inp, inp), dtype=int)