In [10]:
import math
def isPrime(num):
    for itm in range(2, (int(math.sqrt(num)) + 1)):
        if (num % itm == 0):
            return False
    
    return True

In [14]:
isPrime(6)

False

In [32]:
n = int(input("Enter a number: "))

list = []
def findDivisors(input):
    (x, y) = [(item, input//item) for item in range(2, int(math.sqrt(input))+1) if (input % item) == 0]
    print(x, y)
            
findDivisors(n)

Enter a number: 28


NameError: name 'x' is not defined

In [23]:
sum(findDivisors(28))

TypeError: unsupported operand type(s) for +: 'int' and 'tuple'

In [33]:
import numpy as np

In [40]:
a = np.tile([1, 3], (2, 3))
a

array([[1, 3, 1, 3, 1, 3],
       [1, 3, 1, 3, 1, 3]])

In [41]:
a[:,3]

array([3, 3])

In [43]:
np.unravel_index(100)

TypeError: unravel_index() missing required argument 'shape' (pos 2)

In [48]:
np.eye(2, dtype = int).reshape(4, 1).T

array([[1, 0, 0, 1]])

In [49]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [50]:
a = np.arange(10)
f = np.vectorize(lambda x: x+1)
f(a)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [51]:
?np.vectorize

array([[1, 1],
       [1, 1]])

In [54]:
np.full((2,2), 1) == np.ones((2,2))

array([[ True,  True],
       [ True,  True]])

In [55]:
?np.percentile

In [56]:
a = np.array( [7, 10, 2, 4, 13, 16])
med = np.percentile(a, 50)
med

8.5

In [57]:
import pandas as pd

In [58]:
S1 = pd.Series([0, 2, 4, 6, 8, 10, 12])
S2 = pd.Series([0, 3, 6, 9, 12, 15])

In [62]:
S1[S1.isin(~S2)]

Series([], dtype: int64)

In [63]:
S1 = pd.Series([0, 2, 4, 6, 8, 10, 12])
S2 = pd.Series([0, 3, 6, 9, 12, 15])

In [64]:
S1[S1.isin(S2)].index == S2[S2.isin(S1)].index


array([ True, False, False])

In [65]:
b = np.array([(1.5,2,3), (4,5,6)], dtype = float)
b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [69]:
b[:1]

array([[1.5, 2. , 3. ]])